services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dafstoreDB        
      POSTGRES_USER: admin     
      POSTGRES_PASSWORD: 1@2#3$4%
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
